site_name: Research Notebook
site_author: Gregory E. Maurer
#pages:
#    - Home: 'index.md'
#    - Activity Log: 'activitylog.md'
#    - To Do list: 'todo.md'
#    - Sites: 'sites/SitesIndex.md'
theme:
  name: material
repo_url: https://greg.pronghorns.net/EarthSciNotebook/
edit_uri: edit/main/docs/
